# Generated by Django 4.2.3 on 2023-08-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Kontaktlar'},
        ),
    ]
