# Generated by Django 4.2.3 on 2023-08-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='about_company',
        ),
    ]
