# Generated by Django 4.2.3 on 2023-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_company_about_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='logo')),
            ],
            options={
                'verbose_name_plural': 'Partnyorlar',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Şirkət məlumatları'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Kontakt mesajları'},
        ),
    ]
