# Generated by Django 4.2.3 on 2023-08-21 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_partners_alter_company_options_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='adı'),
            preserve_default=False,
        ),
    ]
