# Generated by Django 4.2.3 on 2023-09-27 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_partners_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='haqqımızda'),
        ),
    ]
