# Generated by Django 4.2.3 on 2023-10-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_company_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_company', 'Mövcud şirkət məlumatlarına baxa bilər'), ('add_company', 'Şirkət məlumatları əlavə edə bilər'), ('change_company', 'Şirkət məlumatlarını yeniləyə bilər'), ('delete_company', 'Şirkət məlumatlarını silə bilər')), 'verbose_name_plural': 'Şirkət məlumatları'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_contact', 'Mövcud kotakt mesajlarına baxa bilər'), ('add_contact', 'Kontakt mesajı əlavə edə bilər'), ('change_contact', 'Kontakt mesajını yeniləyə bilər'), ('delete_contact', 'Kontakt mesajını silə bilər')), 'verbose_name_plural': 'Kontakt mesajları'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_partners', 'Mövcud partnyorlara baxa bilər'), ('add_partners', 'Partnyor əlavə edə bilər'), ('change_partners', 'Partnyorları yeniləyə bilər'), ('delete_partners', 'Partnyorları silə bilər')), 'verbose_name_plural': 'Partnyorlar'},
        ),
    ]
