version: '3.3'

services:
  itech_shop_db:
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54034:5432"
    networks:
      - itech-shop-network
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  itech_shop_web:
    restart: always
    build: ./src
    networks:
      - itech-shop-network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./src:/src
      - ./src/itech_shop:/src/itech_shop
      - ./src/static:/src/static
      - ./src/media:/src/media
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - itech_shop_db
volumes:
  postgres_data:
    driver: local
  static:
    driver: local
  media:
    driver: local
  web:
    driver: local

networks:
  itech-shop-network:
    driver: bridge