# Generated by Django 4.2.3 on 2023-07-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('image', models.ImageField(upload_to='products/', verbose_name='şəkil')),
            ],
        ),
    ]
