# Generated by Django 4.2.3 on 2023-10-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_services', 'Mövcud servislərə baxa bilər'), ('add_services', 'Servis əlavə edə bilər'), ('change_services', 'Servisləri yeniləyə bilər'), ('delete_services', 'Servisləri silə bilər')), 'verbose_name_plural': 'Servislər'},
        ),
    ]
