# Generated by Django 4.2.3 on 2023-08-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_product_description_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
