# Generated by Django 4.2.3 on 2023-08-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Məhsullar'},
        ),
    ]
