# Generated by Django 4.2.3 on 2023-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlıq')),
                ('value', models.CharField(max_length=255, verbose_name='dəyər')),
            ],
            options={
                'verbose_name_plural': 'Atributlar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(null=True, related_name='products', to='products.attributes'),
        ),
    ]
