# Generated by Django 4.2.3 on 2023-08-28 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlıq')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='banner/', verbose_name='şəkil')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'Endirim'},
        ),
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='məbləğ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'FİX'), ('percentage', 'FAİZ')], default='fixed', max_length=50, verbose_name='endirim növü'),
        ),
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ManyToManyField(related_name='discounts', to='products.product'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlıq')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('products', models.ManyToManyField(related_name='collections', to='products.product')),
            ],
        ),
    ]
