# Generated by Django 4.2.3 on 2023-08-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_banner_alter_discount_options_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'Məhsullar'},
        ),
    ]
