# Generated by Django 4.2.3 on 2023-08-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Məhsullar'},
        ),
    ]
