# Generated by Django 4.2.3 on 2023-09-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_attributes_show_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='dəyər')),
            ],
            options={
                'verbose_name_plural': 'Atribut Dəyərləri',
            },
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.ManyToManyField(related_name='products', to='products.attributevalues')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='attributes',
            name='attribute_values',
            field=models.ManyToManyField(related_name='values', to='products.attributevalues'),
        ),
    ]
