# Generated by Django 4.2.3 on 2023-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_attributevalues_remove_attributes_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='show_cart',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='show_cart',
            field=models.BooleanField(default=False, verbose_name='Kartın üstünə gəldikdə göstərilsin'),
        ),
    ]
