# Generated by Django 4.2.3 on 2023-09-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_attributes_show_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='attribute_values',
            field=models.ManyToManyField(related_name='products', to='products.attributevalues'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attributes',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.attributes'),
        ),
    ]
