# Generated by Django 4.2.3 on 2023-09-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productattribute_attribute_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attributes',
        ),
    ]
