# Generated by Django 4.2.3 on 2023-09-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_productattribute_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='attributevalues',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='products.attributes'),
        ),
    ]
