# Generated by Django 4.2.3 on 2023-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_attributes_attribute_values_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'Məhsul Atributları'},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='show_cart',
        ),
        migrations.AddField(
            model_name='attributes',
            name='show_cart',
            field=models.BooleanField(default=False, verbose_name='Kartın üstünə gəldikdə göstərilsin'),
        ),
    ]
