# Generated by Django 4.2.3 on 2023-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='home_page_products', to='products.product')),
            ],
        ),
    ]
