# Generated by Django 4.2.3 on 2023-09-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_homepageproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name_plural': 'Təkliflər'},
        ),
        migrations.AlterModelOptions(
            name='homepageproducts',
            options={'verbose_name_plural': 'Ana Səhifəyə düşəcək məhsullar'},
        ),
    ]
