# Generated by Django 4.2.3 on 2023-10-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_productcolor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_attributes', 'Mövcud attributlara baxa bilər'), ('add_attributes', 'Attribut əlavə edə bilər'), ('change_attributes', 'Attributları yeniləyə bilər'), ('delete_attributes', 'Attributları silə bilər')), 'verbose_name_plural': 'Atributlar'},
        ),
        migrations.AlterModelOptions(
            name='attributevalues',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_attributevalues', 'Mövcud attribut dəyərlərinə baxa bilər'), ('add_attributevalues', 'Attribut dəyəri əlavə edə bilər'), ('change_attributevalues', 'Attribut dəyərlərini yeniləyə bilər'), ('delete_attributevalues', 'Attribut dəyərlərini silə bilər')), 'verbose_name_plural': 'Atribut Dəyərləri'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_banner', 'Mövcud bannerlərə baxa bilər'), ('add_banner', 'Banner əlavə edə bilər'), ('change_banner', 'Bannerləri yeniləyə bilər'), ('delete_banner', 'Bannerləri silə bilər')), 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_category', 'Mövcud kateqoriyalara baxa bilər'), ('add_category', 'Kateqoriyalar əlavə edə bilər'), ('change_category', 'Kateqoriyaları yeniləyə bilər'), ('delete_category', 'Kateqoriyaları silə bilər')), 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_collection', 'Mövcud təkliflərə baxa bilər'), ('add_collection', 'Təklif əlavə edə bilər'), ('change_collection', 'Təklifləri yeniləyə bilər'), ('delete_collection', 'Təklifləri silə bilər')), 'verbose_name_plural': 'Təkliflər'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_discount', 'Mövcud endirimlərə baxa bilər'), ('add_discount', 'Endirim əlavə edə bilər'), ('change_discount', 'Endirimləri yeniləyə bilər'), ('delete_discount', 'Endirimləri silə bilər')), 'verbose_name_plural': 'Endirim'},
        ),
        migrations.AlterModelOptions(
            name='homepageproducts',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_homepageproducts', 'Ana səhifədəki məhsullara baxa bilər'), ('add_homepageproducts', 'Ana səhifədə görünəcək məhsulları təyin edə bilər'), ('change_homepageproducts', 'Ana səhifədə görünəcək məhsulları yeniləyə bilər'), ('delete_homepageproducts', 'Ana səhifədə görünəcək məhsulları silə bilər')), 'verbose_name_plural': 'Ana Səhifəyə düşəcək məhsullar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_product', 'Mövcud məhsullara baxa bilər'), ('add_product', 'Məhsul əlavə edə bilər'), ('change_product', 'Məhsulları yeniləyə bilər'), ('delete_product', 'Məhsulları silə bilər')), 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_productattribute', 'Mövcud məhsul attributlarına baxa bilər'), ('add_productattribute', 'Məhsul üçün attribut əlavə edə bilər'), ('change_productattribute', 'Məhsul attributlarını yeniləyə bilər'), ('delete_productattribute', 'Məhsul attributlarını silə bilər')), 'verbose_name_plural': 'Məhsul Atributları'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_productcolor', 'Mövcud məhsul rənglərinə baxa bilər'), ('add_productcolor', 'Məhsul üçün rəng əlavə edə bilər'), ('change_productcolor', 'Məhsul rənglərini yeniləyə bilər'), ('delete_productcolor', 'Məhsul rənglərini silə bilər')), 'verbose_name_plural': 'Məhsul Rəngləri'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_productimage', 'Mövcud məhsul şəkillərinə baxa bilər'), ('add_productimage', 'Məhsul üçün şəkil əlavə edə bilər'), ('change_productimage', 'Məhsul şəkillərini yeniləyə bilər'), ('delete_productimage', 'Məhsul şəkillərini silə bilər')), 'verbose_name_plural': 'Məhsul Şəkilləri'},
        ),
    ]
