# Generated by Django 4.2.3 on 2023-10-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_attributes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_product', 'Mövcud məhsullara baxa bilər'), ('add_product', 'Məhsul əlavə edə bilər'), ('change_product', 'Məhsulları yeniləyə bilər'), ('delete_product', 'Məhsulları silə bilər')), 'verbose_name_plural': 'Məhsullar'},
        ),
    ]
